version: "3.8"

services:
  gatsby:
    build:
      context: .
      dockerfile: ./docker-config/gatsby-ui/Dockerfile
    ports:
      - "8000:8000"
      - "6006:6006"
    volumes:
      - /app/node_modules
      - ./app:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/ # https://blog.konnor.site/javascript/setting-up-gatsby-with-docker/
      - GATSBY_TELEMETRY_DISABLED=1 # https://clubmate.fi/disable-gatsby-telemetry
    # command: gatsby develop -H 0.0.0.0
